name: rprsnt
favicon: null
layout_spectrum: 0.48431702773086727
typography_spectrum: 0.9315988041926175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9994915327988565
  lightness: 0.4024277813732624
  saturation: 0.4742522172164172
  rhythmicContrast: 0.7772579926531762
purpose: []
